In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"Downloads\turnover.csv")

In [3]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [4]:
df.isnull().any()

satisfaction_level       False
last_evaluation          False
number_project           False
average_montly_hours     False
time_spend_company       False
Work_accident            False
left                     False
promotion_last_5years    False
sales                    False
salary                   False
dtype: bool

In [5]:
x=df.iloc[:,0:9].values

In [6]:
y=df.iloc[:,9:10].values

In [7]:
x

array([[0.38, 0.53, 2, ..., 1, 0, 'sales'],
       [0.8, 0.86, 5, ..., 1, 0, 'sales'],
       [0.11, 0.88, 7, ..., 1, 0, 'sales'],
       ...,
       [0.37, 0.53, 2, ..., 1, 0, 'support'],
       [0.11, 0.96, 6, ..., 1, 0, 'support'],
       [0.37, 0.52, 2, ..., 1, 0, 'support']], dtype=object)

In [8]:
y

array([['low'],
       ['medium'],
       ['medium'],
       ...,
       ['low'],
       ['low'],
       ['low']], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le=LabelEncoder()

In [11]:
x[:,8]=le.fit_transform(x[:,8])
y[:,0]=le.fit_transform(y[:,0])

In [12]:
x

array([[0.38, 0.53, 2, ..., 1, 0, 7],
       [0.8, 0.86, 5, ..., 1, 0, 7],
       [0.11, 0.88, 7, ..., 1, 0, 7],
       ...,
       [0.37, 0.53, 2, ..., 1, 0, 8],
       [0.11, 0.96, 6, ..., 1, 0, 8],
       [0.37, 0.52, 2, ..., 1, 0, 8]], dtype=object)

In [13]:
y

array([[1],
       [2],
       [2],
       ...,
       [1],
       [1],
       [1]], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe=OneHotEncoder(categorical_features=[8])
ohe1=OneHotEncoder(categorical_features=[0])

In [16]:
x=ohe.fit_transform(x).toarray()
y=ohe1.fit_transform(y).toarray()

C:\Users\nvijj\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\nvijj\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
C:\Users\nvijj\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of in

In [17]:
x

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [18]:
y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [19]:
x=x[:,1:]
y=y[:,1:]

In [20]:
x

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [21]:
y

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
x_train

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
y_train

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 0.],
       [1., 0.]])

In [26]:
x_test

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [28]:
x_train

array([[-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
         1.7834899 , -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       ...,
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599]])

In [29]:
y_train

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 0.],
       [1., 0.]])

In [30]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [31]:
y_pred=dt.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5973333333333334

In [32]:
y_pred

array([[0., 1.],
       [0., 1.],
       [0., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [33]:
x_test

array([[-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
         1.7834899 , -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       ...,
       [ 4.2587746 , -0.23282697, -0.22922447, ..., -0.41086453,
         1.7834899 , -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599]])

In [34]:
y_test

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [35]:
x_train

array([[-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
         1.7834899 , -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       ...,
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599],
       [-0.23480933, -0.23282697, -0.22922447, ..., -0.41086453,
        -0.56069844, -0.14646599]])

In [36]:
y_train

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 0.],
       [1., 0.]])